/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_dma.h"
#include "fsl_common.h"
#include "fsl_i2s.h"
#include "fsl_i2s_dma.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* BOARD_InitPeripherals defines for FLEXCOMM4 */
/* Definition of peripheral ID */
#define FC4_I2S_TX_PERIPHERAL ((I2S_Type *)FLEXCOMM4)
/* Definition of the clock source frequency */
#define FC4_I2S_TX_CLOCK_SOURCE 24576000UL
/* Selected DMA channel number. */
#define FC4_I2S_TX_TX_DMA_CHANNEL 9
/* Used DMA device. */
#define FC4_I2S_TX_TX_DMA_BASEADDR DMA0
/* BOARD_InitPeripherals defines for FLEXCOMM5 */
/* Definition of peripheral ID */
#define FC5_I2S_RX_PERIPHERAL ((I2S_Type *)FLEXCOMM5)
/* Definition of the clock source frequency */
#define FC5_I2S_RX_CLOCK_SOURCE 24576000UL
/* Selected DMA channel number. */
#define FC5_I2S_RX_RX_DMA_CHANNEL 10
/* Used DMA device. */
#define FC5_I2S_RX_RX_DMA_BASEADDR DMA0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2s_config_t FC4_I2S_TX_config;
extern dma_handle_t FC4_I2S_TX_TX_Handle;
extern i2s_dma_handle_t FC4_I2S_Tx_Handle;
extern const i2s_config_t FC5_I2S_RX_config;
extern dma_handle_t FC5_RX_Handle;
extern void * fc5RxData;
extern i2s_dma_handle_t FC5_I2S_Rx_DMA_Handle;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* I2S DMA callback function for the FC5_I2S_RX component (init. function BOARD_InitPeripherals)*/
extern void fc5_i2s_rx_cb(I2S_Type *,i2s_dma_handle_t *,status_t ,void *);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
